---
openapi: 3.0.0
info:
  title: VaccineProgress
  description: A service to help better understand the current vaccine progress for COVID-19 and depict what countries need assistance.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
  version: 0.0-oas3
servers:
- url: 'http://localhost:8080'
paths:
  /raw:
    get:
      tags:
      - RAW
      description: Returns the raw data of the entire dataset including all countries and all data.
      operationId: VaccineProgress.raw
      responses:
        "200":
          description: Gathers raw data and cleanses to create accurate raw data for our model
          content:
            application/json:
              schema: {}
  /final:
    get:
      tags:
      - FINAL
      description: Returns the final result in a table fashion for countries in need of assistance
      operationId: VaccineProgress.show_final
      responses:
        "200":
          description: Calculates and displays the final verdict for if a country requires assistance or not.
          content:
            application/json:
              schema: {}
  /test:
    get:
      tags:
      - TEST
      description: test
      operationId: VaccineProgress.test
      responses:
        "200":
          description: test
          content:
            application/json:
              schema: {}
components: {}
